/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lamfamily' at '9/19/16 10:34 PM' with Gradle 2.13
 *
 * @author lamfamily, @date 9/19/16 10:34 PM
 */

import org.joda.time.LocalTime;

public class Library {
    public boolean someLibraryMethod() {
        LocalTime currentTime = new LocalTime();
        System.out.println("The current local time is: " + currentTime);

        return true;
    }
}
